# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from base_class import BrowserSetup

class TestAddnote(BrowserSetup):
  # def setup_method(self, method):
  #   self.driver = webdriver.Firefox()
  #   self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_addnote(self):
    # Test name: add_note
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("http://localhost:5173/")
    # 2 | setWindowSize | 1108x1040 | 
    self.driver.set_window_size(1108, 1040)
    # 3 | click | id=title | 
    self.driver.find_element(By.ID, "title").click()
    # 4 | type | id=title | A new note
    self.driver.find_element(By.ID, "title").send_keys("A new note")
    # 5 | click | id=body | 
    self.driver.find_element(By.ID, "body").click()
    # 6 | type | id=body | A new body of text
    self.driver.find_element(By.ID, "body").send_keys("A new body of text")
    # 7 | click | id=delete-note-0 | 
    self.driver.find_element(By.ID, "delete-note-0").click()
    # 8 | click | css=#empty-state-icon path | 
    self.driver.find_element(By.CSS_SELECTOR, "#empty-state-icon path").click()
  
