# fly.toml app configuration file generated for simple-notes on 2023-07-13T10:56:41-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "simple-notes"
primary_region = "lax"

[build]
  builder = "paketobuildpacks/builder:full"

# needed to run fly volume create simple_notes_data -r lax --size 1
# in order to get a 1gb volume, in region lax (las angeles)
[mounts]
  source="simple_notes_data"
  destination="/data"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
