# fly.toml app configuration file generated for simply-notes on 2023-09-14T13:59:33-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "simply-notes"
primary_region = "lax"

[build]
  builder = "paketobuildpacks/builder:full"

[env]
  PORT = "8080"

[[mounts]]
  source = "simple_notes_data"
  destination = "/data"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
