# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test Frontend

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: "Install Node"
      uses: actions/setup-node@v1
      with:
        node-version: "18.x"
    - uses: actions/checkout@v3
    # checkout@v3 is for checking out source-code. Before that, our codebase has not been installed!
    - name: "Install global packages"
      run: npm install -g yarn
    - name: Install yarn dependencies
      working-directory: ./client/
      run: yarn install
    - name: set vite base url for local testing
      run: echo VITE_BASE_URL=http://localhost:5000 > ./client/.env.local
    - name: start yarn
      working-directory: ./client/
      run: yarn run vite &

    # - uses: actions/checkout@v3  # duplicate, as it was done earlier
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
        # I remove upgrade of pip, felt like it wasn't necessary
      run: |
        pip install pytest
        if [ -f client/tests/requirements.txt ]; then pip install -r client/tests/requirements.txt; fi
        if [ -f server/requirements.txt ]; then pip install -r server/requirements.txt; fi
    - name: run backend
      run: python3 server/app.py &

    - uses: browser-actions/setup-chrome@v1
    - run: chrome --version
    # install chromedriver
    - uses: nanasess/setup-chromedriver@v2
    - run: |
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

    # geckodriver is no longer needed. But I might hold onto it for future use
    - uses: browser-actions/setup-geckodriver@latest
    - run: geckodriver --version
    - run: which geckodriver
    - name: Test frontend with pytest & firefox & selenium
      run: |
        pytest client/tests/
