# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test Frontend

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: "Install Node"
      uses: actions/setup-node@v1
      with:
        node-version: "18.x"
    - name: "Install global packages"
      run: npm install -g yarn
    - name: Install yarn dependencies
      run: yarn install
    - name: config for port
      run: echo VITE_BASE_URL=http://localhost:5000 > client/.env.local
    - name: start yarn
      run: yarn dev &

    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f client/tests/requirements.txt ]; then pip install -r client/tests/requirements.txt; fi
        if [ -f server/requirements.txt ]; then pip install -r server/requirements.txt; fi
    - name: run backend
      run: python3 server/app.py &

    - uses: browser-actions/setup-geckodriver@latest
    - run: geckodriver --version
    - run: which geckodriver
    - name: Test frontend with pytest & firefox & selenium
      run: |
        pytest client/tests/
